title: cybersf
tagline: A Penetration Testing Framework
author: khulnasoft
url: https://khulnasoft.com
permalink: pretty

remote_theme: pmarsceill/just-the-docs
color_scheme: nil
aux_links:
  "cybersf on GitHub":
    - "https://github.com/khulnasoft/cybersf"
footer_content: "Copyright &copy; 2023 khulnasoft. Distributed with the <a href=\"https://github.com/khulnasoft/cybersf/tree/main/LICENSE\">MIT license.</a>"

plugins:
  - jekyll-seo-tag
